### ISSUE TITLE
多次register，unregister之后，每次doWork都会多调用一次

### ISSUE THREAD

**Issue by liunewshine** [gyf-dev/Cactus#12]
第一次register，doWork调用1次；然后unregister，
再次register，doWork调用2次；然后unregister，
再次register，doWork调用3次；然后unregister
...........

**Comment by gyf-dev** [comment]
你说的是doWork的times参数吧，该参数的意思是表示服务已经启动的次数

**Comment by liunewshine** [comment]
25年英国是

**Comment by gyf-dev** [comment]
我这边测试没问题，看视频演示：https://pan.baidu.com/s/1nsGrXr61mg5tNd3D5ZMd6w 提取码：Y46r
