### ISSUE TITLE
Bad notification for startForeground: java.lang.IllegalArgumentException: Channel does not exist

### ISSUE THREAD

**Issue by zhoufeng1213** [gyf-dev/Cactus#17]
设备：华为mate20    android10

**Comment by gyf-dev** [comment]
怎么使用的？

**Comment by zhoufeng1213** [comment]
1、implementation 'com.gyf.cactus:cactus:1.1.3-beta05'
2、在application的oncreate中：
        Intent intent = new Intent(this,SplashActivity.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        PendingIntent pendingIntent = PendingIntent.getActivity(this,1,intent,
                PendingIntent.FLAG_UPDATE_CURRENT);
        Cactus.getInstance()
                .isDebug(false)
                .setPendingIntent(pendingIntent)
                .setBackgroundMusicEnabled(false)
                .addCallback(new CactusCallback() {
                    @Override
                    public void doWork(int i) {

                    }

                    @Override
                    public void onStop() {

                    }
                })
                .register(this);
3、启动应用后点击home键回到桌面，过一会就会报这个错误

**Comment by gyf-dev** [comment]
那你得把hideNotificationAfterO设置为false，不然也没办法解决

**Comment by zhoufeng1213** [comment]
好的，谢谢
