### ISSUE TITLE
怎么和Service结合呢？

### ISSUE THREAD

**Issue by liunewshine** [gyf-dev/Cactus#9]
请问下，我有个高德地图定时上传位置的Service，怎么和这个库结合呢？
只需要注册这个库以后，Service就能自动保活吗？

**Comment by gyf-dev** [comment]
把你的Service删除，使用api addCallback来处理，因为Cactus也是在Service来运行的

**Comment by liunewshine** [comment]
![image](https://user-images.githubusercontent.com/7698511/70029769-c16a9000-15e2-11ea-8cae-a3f6ffc9d406.png)
但是这个service是高德提供的，没法做更改
@gyf-dev

**Comment by gyf-dev** [comment]
那你接入Cactus注册就可以了，接入就可以提高进程优先级了

**Comment by liunewshine** [comment]
好的，非常感谢
